mopro-core/src/middleware/circom/mod.rs

Get public inputs from witness and zkey config

chore(core): get inputs from witness

---

scripts/build_ios.sh

- throw error is ios script fails
- lint

fix: handle ios script exit

---

.github/workflows/build-and-test.yml

- improve CI time (decrease install circom time from 3~5 minutes to 1s)

chore: download circom in ci

---

.github/workflows/build-and-test.yml
.gitignore
Cargo.lock
README.md
anon-aadhaar-config.toml
config-ci.toml
config-complex.toml
config-example.toml
mopro-core/Cargo.toml
mopro-core/README.md
mopro-core/build.rs
mopro-core/src/middleware/circom/mod.rs
mopro-ffi/Cargo.toml
mopro-ffi/README.md
scripts/build_android.sh
scripts/build_ios.sh
scripts/prepare_ci.sh
scripts/update_bindings.sh
templates/mopro-example-app/mopro-config.toml

**TODO**
**benchmark**
- keccak proof in `mopro-core` test (10x faster)
| method | `witness-rs` | `circom-compat` |
|--| --| --|
| witness generation time | 329.73ms  | 3.08s |
- keccak proof in ios device (release mode) (12x faster)
| method | `witness-rs` | `circom-compat` |
|--| --| --|
| witness generation time | 32.42ms  | 409.41ms  |

feat(witness): init witness repo, try witness-rs in keccak proof

---

README.md
mopro-core/build.rs
scripts/cli/install_deps.sh

https://github.com/oskarth/mopro/issues/119
- Default to simpler circuit
- Download artifacts to simulate mopro prepare

fix(cli,core): Fix first mopro deps error

---

.gitignore
Cargo.toml
README.md
anon-aadhaar-config.toml
ark-zkey/README.md
config-ci.toml
config-complex.toml
config-example.toml
mopro-android/Example/build.gradle.kts
mopro-android/README.md
mopro-cli/README.md
mopro-cli/src/init.rs
mopro-cli/src/utils.rs
mopro-core/README.md
mopro-core/src/middleware/circom/mod.rs
templates/mopro-example-app/.gitignore
web-prover/src/app/footer.tsx

- Run through all cli commands and fix `Cargo.toml` and other path
- Update `oskarth/mopro` to `zkmopro/mopro`
- Add options in mopro-cli commands

fix: fix morpo cli test and update path

---

Cargo.lock
mopro-core/Cargo.toml
mopro-core/src/middleware/gpu_explorations/arkworks_pippenger.rs
mopro-core/src/middleware/gpu_explorations/trapdoortech_zprize_msm/mod.rs

- enable parallel feature https://github.com/Trapdoor-Tech/TrapdoorTech-zprize-mobile-harness/blob/master/Cargo.toml#L24
- result (on simulator)
(on iPhone 12 mini)

feat: enable parallel in gpu-benchmarks

---

docs/docs/performance.md

- add benchmark result in different circuits

doc: add new benchmark result

---

mopro-ffi/src/circom/mod.rs

feat: build witness in background thread

---

docs/docs/performance.md

- update Tachyon benchmark https://github.com/vivianjeng/tachyon-circom-example
- witness calculation: loading `.dat` + calculate `full_assginments`
- proof generation: QAP + `CreateProofWithAssignmentZK`

doc: update tachyon benchmark result

---

test-e2e/android/app/src/main/assets/fibonacci_pk.bin
test-e2e/android/app/src/main/assets/fibonacci_srs.bin
test-e2e/android/app/src/main/assets/fibonacci_vk.bin
test-e2e/android/app/src/main/java/com/mopro/mopro_app/FibonacciComponent.kt
test-e2e/android/app/src/main/java/com/mopro/mopro_app/MainActivity.kt

Added a sample of using Halo2 in Android as well as improved the UI to switch between Halo2 and Circom circuit samples intuitively.

(feat: android) Sample of using Halo2 in Android

---

docs/docusaurus.config.ts
docs/src/css/custom.css

doc: add search bar

---

docs/docs/FAQ.md
docs/docs/community.md
docs/versioned_docs/version-0.1.0/FAQ.md
docs/versioned_docs/version-0.1.0/community.md

doc: update talks and FAQ

---

cli/src/build.rs
cli/src/init.rs
cli/src/style.rs

Improve the visibility of the unchecked item
- Before
- After

chore: improve checkbox UI

---

Cargo.lock
cli/src/build.rs
cli/src/create.rs
cli/src/init.rs
cli/src/template/init/Cargo.toml
cli/src/template/mopro-wasm-lib/.cargo/config.toml
cli/src/template/mopro-wasm-lib/Cargo.toml
cli/src/template/mopro-wasm-lib/README.md
cli/src/template/mopro-wasm-lib/rust-toolchain.toml
cli/src/template/mopro-wasm-lib/src/lib.rs
cli/src/template/web/index.js
test-e2e/mopro-wasm-lib/Cargo.toml

- Added "mopro-wasm-lib" in template 
- "mopro-wasm-lib" is use "mopro-wasm" in main branch

Fixed mopro cli for web platform

---

.github/workflows/build-and-test.yml
Cargo.lock
cli/src/build.rs
cli/src/style.rs
mopro-ffi/src/app_config/ios.rs
mopro-ffi/src/app_config/mod.rs
mopro-ffi/src/circom/mod.rs
mopro-ffi/src/circom/serialization.rs
mopro-ffi/src/lib.rs
mopro-wasm/src/app_config/web.rs
test-e2e/Cargo.toml

The `cargo.toml` in `test-e2e` contains a temporary fix for a known `uniffi` issue (https://github.com/mozilla/uniffi-rs/issues/2346). We can remove it as soon as they release the next version.

Integrate clippy into GitHub workflow

---

.github/workflows/build-and-test.yml
Cargo.lock
cli/src/template/mopro-wasm-lib/src/lib.rs
mopro-wasm/Cargo.toml
mopro-wasm/src/app_config/web.rs
mopro-wasm/tests/wasm.rs
test-e2e/mopro-wasm-lib/src/lib.rs

- halo2 crate should be optional
- It will show the building logs immediately

chore: improve mopro-wasm

---

README.md
docs/docs/performance.md
docs/versioned_docs/version-0.1.0/performance.md

close #266 
close #44 
ref: https://github.com/zkmopro/android-benchmark-app

doc: update android/iOS benchmark on readme

---

circom-prover/src/witness.rs
mopro-ffi/src/circom/mod.rs

- update this change https://github.com/zkmopro/witnesscalc_adapter/pull/5

chore: update witnesscalc api

---

mopro-ffi/src/lib.rs

fix: fix missing types

---

docs/versioned_docs/version-0.1.0/FAQ.md
docs/versioned_docs/version-0.1.0/community.md
docs/versioned_docs/version-0.1.0/intro.md

doc: fix grammar

---

circom-prover/src/prover/ark_circom/zkey.rs
cli/src/config.rs
docs/docs/performance.md
docs/versioned_docs/version-0.1.0/performance.md

chore: fix some typos

---

README.md
docs/docs/community.md
docs/docs/getting-started.md
docs/docs/intro.md
docs/docs/mopro-wasm.md
docs/docs/performance.md
docs/docs/setup/ios-setup.md
docs/versioned_docs/version-0.0.1/community.md
docs/versioned_docs/version-0.0.1/intro.md
docs/versioned_docs/version-0.1.0/community.md
docs/versioned_docs/version-0.1.0/getting-started.md
docs/versioned_docs/version-0.1.0/intro.md
docs/versioned_docs/version-0.1.0/mopro-wasm.md
docs/versioned_docs/version-0.1.0/performance.md
docs/versioned_docs/version-0.1.0/setup/ios-setup.md
mopro-ffi/README.md
mopro-wasm/README.md

https://github.com/zkmopro/mopro/pull/335
https://github.com/zkmopro/mopro/pull/332

fix grammar

---

mopro-ffi/src/circom/mod.rs
mopro-ffi/src/halo2/mod.rs

chore: improve readability

---

cli/src/init.rs
cli/src/template/init/Cargo.toml

fix: fix template project name

---

cli/src/template/init/README.md

- fix: https://github.com/zkmopro/mopro/pull/362/files

fix: fix numeration in README.md

---

circom-prover/src/prover/ethereum.rs
mopro-ffi/src/circom/ethereum.rs
mopro-ffi/src/circom/mod.rs
mopro-ffi/src/lib.rs
test-e2e/android/app/src/main/java/com/mopro/mopro_app/MultiplierComponent.kt
test-e2e/ios/mopro-test/ContentView.swift

From proof

---

Cargo.lock
circom-prover/Cargo.toml
circom-prover/README.md
test-e2e/Cargo.toml

- bump `circom-prover` version

Publish circom prover

---

cli/src/create/flutter.rs

align with react-native
https://github.com/zkmopro/mopro/blob/c092d0daa08e684bbd61782f8148ddabbcb86c55/cli/src/create/react_native.rs#L21

fix: fix flutter app name

---

docs/blog/2025-05-08-dev-exp.md

Added Developer Experience Blog

AA x Mopro

---

docs/docs/performance.md

Halo2 benchmark

---

Cargo.lock
cli/src/build.rs
cli/src/init/noir.rs
cli/src/template/circom/lib.rs
cli/src/template/halo2/lib.rs
cli/src/template/init/README.md
cli/src/template/init/src/lib.rs
cli/src/template/mopro-wasm-lib/src/lib.rs
cli/src/template/noir/lib.rs
cli/src/utils.rs
mopro-ffi/Cargo.toml

- add tests in `src/lib.rs`
- add `#[uniffi::export]` examples
- add `#[wasm_bindgen]` examples
- update README
- (fix Rust dependencies, it is updated in `noir-rs`)

feat: add tests and example usages

---

Cargo.lock
circom-prover/Cargo.toml
circom-prover/README.md

- only generate witness: https://crates.io/crates/circom-witnesscalc

feat: use crates version of circom-witnesscalc

---

cli/src/constants.rs
cli/src/style.rs
cli/src/utils.rs
docs/docs/architectures.md
docs/sidebars.ts

doc: architecture, feat: add CLI descriptions

---

docs/docs/architectures.md
docs/docs/intro.md
docs/src/components/ArchitectureDiagram/architectureData.ts
docs/src/components/ArchitectureDiagram/index.tsx
docs/src/components/ArchitectureDiagram/styles.module.css

- complete #498
- Added interactive architecture diagram to the https://zkmopro.org/docs/intro
- Created reusable React component with zoom, pan, and tooltip functionality
**Overview:**
**Hover tooltips for details:**
- `docs/docs/intro.md`: Added architecture overview section with embedded interactive diagram
- `docs/docs/architectures.md`: Minor formatting fix for consistency
- `ArchitectureDiagram component`: New interactive React component with:
- Zoomable and pannable SVG diagram
- Hover tooltips with detailed component descriptions
- Theme-aware styling for light/dark modes
- Comprehensive architecture data covering all mopro layers
- Interactive Navigation: Users can zoom and pan to explore different parts of the architecture
- Rich Tooltips: Hover over components to see detailed …

docs: add interactive diagram for mopro architecture

---

cli/src/create/flutter.rs
cli/src/update.rs

exposed functions, shared utils, simplified template

---

.github/workflows/build-and-test.yml

- Added steps to install Clippy and rustfmt components in the GitHub Actions workflow for enhanced code quality checks.

ci: add Clippy and rustfmt installation steps to build workflow
