- mopro-core/Cargo.toml
- mopro-ffi/Cargo.toml
Fixes https://github.com/oskarth/mopro/issues/1
This commit uses a forked version of wasmer to workaround memory limits when running ark-circom WitnessCalculator on a real iOS device.
See https://github.com/wasmerio/wasmer/commit/09c7070 for details. Thanks to philsippl for helping identify this fix.
Note that patch.crates-io ensures we are using our forked version of wasmer for all dependencies. Since we might build from mopro-core or mopro-ffi we need to change both repositories. We can confirm if the forked version is used everywhere with `cargo tree | grep wasmer`.
With this patch, we change the minimum pages from 65536 to 2000, which seems to do the trick:
```
wasmer/memory.rs: Using memory hack to work around memory limits
wasmer/memory.rs: Old minimum pages: 65536 pages …
```
> fix(core,ffi): wasmer memory limits to run on real iOS device

- mopro-ffi/src/lib.rs
- mopro-ffi/src/mopro.udl
- mopro-ffi/tests/bindings/test_mopro.swift
- mopro-ffi/tests/bindings/test_mopro_keccak.swift
- mopro-ios/MoproKit/Example/MoproKit/ViewController.swift
- **Serialization:** `Fr` -> `BigUInt` -> `String`
- **Deserialization:** `String` -> `BigUInt` -> `Fr`
- Add tests for scalar field input: `21888242871839275222246405745257275088548364400416034343698204186575808495616`
> fix(core, ffi): should accept bigint inputs

- mopro-core/src/middleware/circom/mod.rs
- mopro-ffi/src/lib.rs
- mopro-ffi/src/mopro.udl
- mopro-ios/MoproKit/Include/moproFFI.h
- `verify_proof2`: verify proof with arkzkey
> feat(core): verify proof with arkzkey

- .github/workflows/build-and-test.yml
Simpler minimal step that should work and cut down CI time in half.
Can optimize further in follow up PRs
> ci: Build iOS and Android in parallel

- mopro-ios/MoproKit/Bindings/mopro.swift
- mopro-ios/MoproKit/Include/moproFFI.h
- fix uniffi-0.25 linker problem https://github.com/mozilla/uniffi-rs/issues/1922
- `uniffi-bindgen` should be overwritten if `uniffi` version updated
https://github.com/oskarth/mopro/blob/2afe32041f89070e6996da8b38ec192fcd8dfe5f/scripts/prepare.sh#L136-L142
> fix(ios): fix package name

- mopro-core/src/middleware/circom/serialization.rs
- mopro-ffi/src/lib.rs
- mopro-ffi/src/mopro.udl
- mopro-ffi/tests/bindings/test_mopro.kts
- mopro-ffi/tests/bindings/test_mopro.swift
- mopro-ios/MoproKit/Bindings/mopro.swift
- mopro-ios/MoproKit/Include/moproFFI.h
- core: use `ethereum::Proof` to convert proof
- ffi: convert `U256` data to `string`
- usage:
- kotlin
```kotlin
var convertProofResult = convertProof(generateProofResult.proof)
var convertInputsResult = convertInputs(generateProofResult.inputs)
```
- swift
```swift
let convertProofResult = convertProof(proof: generateProofResult.proof)
let convertInputsResult = convertInputs(inputs: generateProofResult.inputs)
```
> Convert proof, inputs for smart contract

- mopro-core/src/middleware/gpu_explorations/bin/generate_benchmark_report.rs
FIx of the issue in https://github.com/oskarth/mopro/issues/61#issue-2104544124.
The main problem is that `./scripts/build_ios.sh simulator release` run `cargo build --release`. The build process can now be successfully executed and so is the script.
> fix(generate_benchmark_report): main function exists even when feature is not enabled

- .github/workflows/build-and-test.yml
- README.md
- config-example-android.toml
- config-example.toml
- mopro-core/Cargo.toml
- mopro-core/build.rs
- scripts/_prelude.sh
- scripts/build_android.sh
- scripts/build_ios.sh
- scripts/prepare.sh
- scripts/prepare_ci.sh
- scripts/update_bindings.sh
This PR starts to introduce a more robust way of configuring relevant build options and environment.
Currently there's a big surface area for options, and we still have some hardcoded leftovers. This means we currently have to do things like this: https://github.com/oskarth/mopro/pull/66/files/8e7d9dafaf0538ab84d739ec8a9f42437772df1a#diff-10095d80195138814b66f1d6f5b769b0763cd537d9ef563a28c6d75444a151d5 which makes things very confusing, especially when we have dealing with multiple circuits.
Specify options in a toml file:
```
[build]
device_type = "simulator" # Options: x86_64, simulator, device
build_mode = "release"    # Options: debug, release
[circuit]
dir = "examples/circom/keccak256" # Directory of the circuit
name = "keccak256_256_test"       # Name of the circuit
[dylib] …
```
> feat: Use TOML for config

- .github/workflows/build-and-test.yml
- config-ci.toml
- scripts/prepare.sh
- scripts/prepare_ci.sh
- add target check for android devices
- fix ci: the device type is `x86_64`
> Fix: toml config

- mopro-core/src/middleware/gpu_explorations/mod.rs
- mopro-ios/MoproKit/Bindings/mopro.swift
- mopro-ios/MoproKit/Example/MoproKit.xcodeproj/project.pbxproj
- mopro-ios/MoproKit/Example/MoproKit/MSMBenchmarkViewController.swift
- mopro-ios/MoproKit/Example/MoproKit/ViewController.swift
- mopro-ios/README.md
> we are aiming to integrate the previous work into IOS Example project
| Algorithm   | Avg Timing | Compare to baseline <br>(arkwork-msm)</br> |
| ----------- | --------------- |:------------------------------------------:|
| arkworks-msm | in ms           |                     -                      |
| Algo. A     | in ms           |                    in %                    |
| Algo. B     | in ms           |                    in %                    |
- [report](https://hackmd.io/OGYdUUsoQzump7uLB5YqKg)
> feat(ios): added basic UI in MSM Benchmark

- ark-zkey/src/lib.rs
- mopro-core/examples/circom.rs
- mopro-core/src/middleware/circom/mod.rs
- mopro-ffi/src/lib.rs
- mopro-ffi/src/mopro.udl
- mopro-ffi/tests/bindings/test_mopro.kts
- mopro-ffi/tests/bindings/test_mopro.swift
- mopro-ffi/tests/bindings/test_mopro_keccak.kts
- mopro-ffi/tests/bindings/test_mopro_keccak.swift
- mopro-ffi/tests/bindings/test_mopro_keccak2.swift
- mopro-ffi/tests/bindings/test_mopro_rsa.kts
- mopro-ffi/tests/bindings/test_mopro_rsa.swift
- mopro-ios/MoproKit/Bindings/mopro.swift
- mopro-ios/MoproKit/Example/MoproKit.xcodeproj/project.pbxproj
- mopro-ios/MoproKit/Example/MoproKit/FileDownloader.swift
- mopro-ios/MoproKit/Example/MoproKit/KeccakSetupViewController.swift
- mopro-ios/MoproKit/Example/Tests/CircomTests.swift
- mopro-ios/MoproKit/Include/moproFFI.h
Implementation for https://github.com/oskarth/mopro/issues/65
- update `MoproCircom` to initialize with arkzkey and wasm
- download arkzkey and wasm in `KeccakSetupViewController`
- result
**KeccakSetupViewController (this PR)**
```
Download wasm took: 0.6701240539550781s
Download ark key took: 1.6424980163574219s
Initializing arkzkey and wasm took 8.671825051307678s
Proof generation took 1.5237200260162354 seconds.
Proof verification succeeded.
```
**KeccakZkeyViewController (generateProof2)**
```
Initializing arkzkey took 8.844295024871826 seconds.
Proof generation took 1.4890559911727905 seconds.
```
- result in iPhone device (iPhone 12 mini)
(This PR)
(generateProof2)
> initialize mopro with arkzkey and wasm

- .github/workflows/build-and-test.yml
- config-android-ci.toml
- config-example-android.toml
- scripts/build_android.sh
- fix #52 
- cache `toml`, `uniffi-bindgen`
- speed up ~10m with cache
> Fix CI, cache compiled `toml` and `uniffi-bindgen`

- mopro-ffi/src/lib.rs
`cargo fix --lib -p mopro-ffi`
> fix(ffi): Get rid of cargo warnings

- scripts/cli/prepare.sh
- for multiplier.circom, there is no `package.json` so it throws error.
- In `prepare.sh` we can check if there is a `package.json` file then execute `npm install`
> fix: fix npm_install script if there is no package.json

- scripts/cli/build_ios.sh
- use `codesign` in `mopro build --platforms ios` if using dylib
- It will list all apple ids
> fix: codesign dylib in mopro-cli

- .github/workflows/build-and-test.yml
- mopro-cli/README.md
- mopro-cli/src/export.rs
- fix export bindings path
- bindings output
```sh
├── android
│   ├── jniLibs
│   │   └── arm64-v8a
│   │       └── libuniffi_mopro.so
│   └── uniffi
│       └── mopro
│           └── mopro.kt
└── ios
├── Bindings
│   ├── module.modulemap
│   ├── mopro.swift
│   └── moproFFI.h
└── aarch64-apple-ios-sim
└── release
└── libmopro_ffi.a
```
> fix: fix export bindings path

- scripts/cli/build_ios.sh
Fixed a type in `mopro/scripts/cli/build_ios.sh` that prevents running `mopro build --platforms ios` when configured for build mode.
> (fix: cli) Fixed issue with IOS debug mode not able to build

- .github/workflows/build-and-test.yml
Currently, if you change your PR from `Draft` to `Ready to Review` the CI do not run on them. This should enable them to run on such event, as well as on several others:
- **opened (already)**
- _reopened (added)_
- _synchronize (added)_
- _ready_for_review (added)_
> (feat: ci) Added an option to run CI on when a PR is ready for review

- .github/workflows/build-and-test.yml
- templates/mopro-example-app/core/src/lib.rs
Before the `fmt` ci was not checking the issues in the `templates/mopro-example-app`, which resulted in the code not being correctly formatted error when running `cargo fmt  --all -- --check`.
**This PR:**
1. Fixed the code formatting issue.
2. Added the additional check to the ci to catch similar issues.
> Rust formatting fix for `templates/mopro-example-app/core`

- mopro-core/build.rs
- mopro-core/examples/halo2/fibonacci/src/bin/fibonacci.rs
- scripts/cli/prepare.sh
- templates/mopro-example-app/core/circuits/halo2-fibonacci/src/bin/fibonacci.rs
1. **Fixed** an issue with hardcoded names of circuit prepare files (keys and `SRS`), now is adjusted based on the circuit name.
2. **Improved** error reporting and suggesting to the user what the issue might be.
3. **Added** an option to manually add circuit files (if they exist, the `mopro prepare` will avoid regenerating them.
4. **Added** an explicit description of the purpose of the binary in the `example/halo2/fibonacci`
> Improvement to Halo2 Prepare phase 

- .github/workflows/build-and-test.yml
- mopro-core/src/middleware/gpu_explorations/arkworks_pippenger.rs
- mopro-core/src/middleware/gpu_explorations/metal/msm.rs
The current candidate choice for the MSM benchmarking test takes too long. Specifically, running the command below without the `--release` tag introduces significant time delays when generating the benchmarking instance:
```bash
cargo test --features=gpu-benchmarks test_benchmark_msm
```
This PR introduces a lightweight benchmark test using smaller instances, specifically size of 2^10. This allows the tests to be completed within 60 seconds on M3 chips, even without the `--release` flag. Additionally, it includes a test to verify the correctness of the MSM results using both Arkworks built-in EC arithmetic and Arkworks MSM as the expected MSM result.
- Benchmark Tests: Implement lightweight benchmark tests with smaller instances (2^10).
- Correctness Tests: Verify MSM results by comparing …
> test(msm): ci test for msm benchmarks and correctness within proper time

- Cargo.lock
- Cargo.toml
- ark-zkey/Cargo.toml
- mopro-core/Cargo.toml
- mopro-core/build.rs
- mopro-core/examples/circom.rs
- mopro-core/examples/circom/rsa/main.circom
- mopro-core/examples/circom/rsa/main_rsa.circom
- mopro-core/src/middleware/circom/mod.rs
- mopro-core/src/middleware/circom/serialization.rs
- mopro-core/src/middleware/circom/utils.rs
- mopro-ffi/Cargo.toml
- mopro-ffi/build.rs
- mopro-ffi/src/circom.rs
- mopro-ffi/src/halo2.rs
- mopro-ffi/src/lib.rs
- mopro-ffi/src/mopro.udl
- mopro-ffi/tests/bindings/test_mopro.kts
- mopro-ffi/tests/bindings/test_mopro.swift
- mopro-ffi/tests/test_generated_bindings.rs
- research/gpu-exploration-app/core/Cargo.toml
- scripts/prepare.sh
- scripts/prepare_ci.sh
- templates/mopro-example-app/Cargo.toml
- templates/mopro-example-app/core/Cargo.toml
This PR removes the wasm logic as well as the `dylib` and `calc-native-witness` logic. Instead it relies on the [`rust-witness`](https://github.com/zkmopro/rust-witness) package to natively build witnesses. This happens by taking the wasm, compiling to c, then using a macro to automatically write a function that calls the c function to build the witness.
The UDL bindings are very complex right now. Instead of passing paths between the rust side and the mobile side I think it makes more sense to build a dictionary on the rust side for each circuit. Imagine there is a build with 2 circuits: `multiplier2` and `keccak256`. Instead of having `initialize(zkey_path, wasm_path)` we could have `initialize(circuit_name)`, and define the paths to zkeys, witnesses, etc at compile time in rust - which …
> refactor: remove wasm, add native proof generation

- mopro-web/docs/getting-started.md
- templates/mopro-example-app/core/Cargo.toml
This PR updates the docs to instruct the user to clone the `v0.0.1` tag. This should allow us to apply breaking changes to the `main` branch without breaking the docs.
> chore: point docs to v0.0.1 tag

- mopro-ffi/src/circom/mod.rs
Related #196 
This PR switches to use a buffered reader for parsing the zkey. The previous implementation was reading from the filesystem too frequently. The buffered reader prevents excess syscalls.
Performance reading `keccak256_256_test_final.zkey` in `release` mode:
- using `File`: `7.57s`
- using #196: `172.96 ms`
- using `BufReader`: `60 ms`
I think `BufReader` is faster than using #196 because it involves fewer memory copy operations, and avoids reading the final sections of the zkey which are unnecessary for making proofs.
> fix: use BufReader for zkey

- .cargo/config.toml
- Cargo.lock
- mopro-ffi/.cargo/config.toml
- mopro-ffi/Cargo.toml
- mopro-ffi/build.rs
- test-e2e/.cargo/config.toml
Closes #205 
This PR adds an env variable `MOPRO_FFI_LINK_TEST_WITNESS` which controls whether or not `mopro-ffi` will link it's test witnesses. Note that this value is _unset_ in `test-e2e` to ensure that `test-e2e` links it's own witness functions and doesn't rely on functions linked by `mopro-ffi`. This env var is set using a [`.cargo`](https://doc.rust-lang.org/cargo/reference/config.html) directory which is only loaded when cargo is invoked from inside the same directory tree.
This PR also removes the library types specified in `mopro-ffi`. These types should be set in dependent crates.
> Test witness linking

- Cargo.lock
- mopro-ffi/Cargo.toml
- mopro-ffi/src/circom/mod.rs
- mopro-ffi/src/circom/serialization.rs
- mopro-ffi/src/halo2/mod.rs
- mopro-ffi/src/lib.rs
- mopro-ffi/src/mopro.udl
This PR refactors the internal functions to use `anyhow` instead of `MoproError`. The error is wrapped in `MoproError` in the udl functions only to avoid many `map_err` calls in core logic.
Closes #220
> refactor: cleanup error handling

- mopro-ffi/Cargo.toml
- mopro-ffi/build.rs
should not execute `rust-witness` if `circom` feature is not activated
> fix: fix dependencies

- mopro-ffi/src/circom/serialization.rs
- Before: `0` will be serialized as `""`
- This PR: `0` will be serialized as `"0"`
- Add tests for `to_ethereum_proof` and `to_ethereum_inputs`
- Add test for `to_ethereum_inputs_with_zero`
> fix: fix ethereum inputs serialization

- cli/src/template/init/.gitignore
- test-e2e/.gitignore
- test-e2e/src/mopro.udl
- UDL file can now be customized, we should not ignore the udl file
- the `mopro-example-app` has `build` folder that can be ignored
> fix: fix ignore files

- cli/src/build.rs
- cli/src/constants.rs
- docs/docs/setup/web-wasm-setup.md
Hi! Fixed a few typos in code comments and documentation:
- **`build.rs`**: Corrected spelling in a comment (`Archtecture` → `Architecture`, `Andriod` → `Android`).
- **`constants.rs`**: Fixed a typo in a section header (`Architeture` → `Architecture`).
- **`web-wasm-setup.md`**: Fixed a misspelling in documentation (`implmentation` → `implementation`).
> fix: typos in comments and documentation

- docs/docs/setup/rust-setup.md
- docs/versioned_docs/version-0.0.1/getting-started.md
- docs/versioned_docs/version-0.1.0/setup/rust-setup.md
- docs/versioned_docs/version-0.1.0/setup/web-wasm-setup.md
- mopro-ffi/src/app_config/constants.rs
This PR addresses small typos in the documentation and code comments to improve readability and remove inaccuracies.
1. **Updated Titles and Terms:**
- In `constants.rs`, fixed a typo in the header: "Architeture" changed to "Architecture."
- In `web-wasm-setup.md`, corrected the typo "implmentation" to "implementation."
2. **Corrected Spelling Errors:**
- `rust-setup.md`: Fixed "seperated" to "separated."
- `getting-started.md`: Replaced "targetting" with "targeting."
Documentation and code comments should always be clear and accurate. The corrected typos might have confused developers, especially those new to the project.
If you have any thoughts or questions about these changes, feel free to share!
> Typos correction

- docs/README.md
- mopro-wasm/README.md
Old:
"can be served using any static contents hosting service."
New:
"can be served using any static content hosting service."
Reason: The singular "content" is the correct term.
Old:
"Run the fibonacci circuit tests for all backends—"plonk," "hyperplonk," and "gemini"—in the browser in a headless."
New:
"Run the fibonacci circuit tests for all backends—"plonk," "hyperplonk," and "gemini"—in a headless browser."
Reason: The revised phrasing improves clarity and grammatical correctness.
>  Corrections to Static Content and Test Command Wording

- docs/docs/FAQ.md
- docs/docs/community.md
- docs/docs/intro.md
docs/docs/FAQ.md
Before: happens natively in app.
After: happen natively in the app.
Fix: Plural verb agreement + added "the" for correctness.
docs/docs/community.md
Before: takes places.
After: takes place.
Fix: Corrected verb form.
docs/docs/intro.md
Before: in an an early stage.
After: in an early stage.
Fix: Removed duplicate "an."
> Fix Grammar and Clarity in Documentation

- cli/src/template/circom/lib.rs
We forgot to update template code with witness refactor
> fix witness fn type in circom template

- cli/src/template/halo2/lib.rs
I updated the comment in the Halo2 example to clarify that it demonstrates the use of multiple elements for proving and verifying, rather than a "single circuit".
p.s. This avoids confusion and ensures accuracy in the documentation.
> fix: Fix misleading comment in Halo2 circuit example

- mopro-ffi/src/lib.rs
Replaces generic parameter names (in0, in1, in2, in3) with descriptive ones in circom_app and halo2_app macros to enhance code maintainability and self-documentation.
> Improve parameter naming in FFI macros for better code readability

- mopro-ffi/src/app_config/android.rs
- It will be used in `witnesscalc` and `rapidsnark`
- see: https://github.com/bbqsrc/cargo-ndk?tab=readme-ov-file#linking-against-and-copying-libc_sharedso-into-the-relevant-places-in-the-output-directory
> feat: link cpp library with cargo ndk

- Cargo.lock
- circom-prover/Cargo.toml
- mopro-ffi/Cargo.toml
- The semaphore-rs uses the poseidon with `ark-bn254 = "0.5"`
- https://github.com/semaphore-protocol/semaphore-rs/blob/3f6bf6319155f3a708748f14964f7d2bd55cf0a7/Cargo.toml#L13
> bump ark-works version

- mopro-ffi/README.md
Hi! I noticed that the link to the `uniffi` documentation in `mopro-ffi/README.md` was broken — it was moved.
> docs: broken link in  `mopro-ffi/README.md`

- circom-prover/Cargo.toml
- circom-prover/src/prover.rs
- circom-prover/src/prover/rapidsnark.rs
- mopro-ffi/src/circom/ethereum.rs
- mopro-ffi/src/circom/mod.rs
part of #368 
Rapidsnark doesn't support BLS12-381 so this PR only adding `BLS12-381` support on `etherum_input/proof`
> feat/support BLS12-381

- cli/src/constants.rs
- mopro-ffi/src/app_config/constants.rs
- mopro-ffi/src/circom/mod.rs
- test-e2e/src/lib.rs
Fix typos in 4 files
> [!IMPORTANT]
> This is potentially a breaking fix, since `AndriodArchInfo` is in UniFFI crate
> chore: Fix typos

- .github/workflows/build-and-test.yml
- _typos.toml
Add [`typos`](https://github.com/crate-ci/typos) CI step
This PR does these two changes:
* Adds one new config file `_typos.toml` (which was used to avoid false positives in #390 )
* Adds a new step in CI to find typos
> chore: Add `typos` cli tool to CI

- .pre-commit-config.yaml
- _typos.toml
> [!NOTE]
> I've cherry-picked the first commit of #391 - adding of the `_typos.toml` file
> [!TIP]
> I did not add instruction to install `pre-commit` in README, since you put prerequisites in your 
> guide here: https://zkmopro.org/docs/prerequisites - so probably we ought to add instructions:
> 1. to install the `pre-commit` binary itself
> 2. to install the pre-commit config of this repo by running `pre-commit install`
This PR adds the wonderful [pre-commit](https://pre-commit.com) tool for pre-commit (and push) hooks.
I've added three steps - running:
* `typos` (see #391 )
* `cargo fmt`
* `cargo clippy`
> chore: Add `pre-commit`

- .github/workflows/build-and-test.yml
Replace `actions/setup-java@v3` with `actions/setup-java@v4` [current release v4.4.0](https://github.com/actions/setup-java/releases/tag/v4.4.0) to move to the Node.js 20 runtime and keep receiving the latest fixes and features
> Upgrade setup-java action to v4

- README.md
- docs/docs/performance.md
This PR introduces Noir benchmark results to the project, updating both the main `README.md` and the detailed performance documentation in `docs/docs/performance.md`.
- related issue: #414
> docs: noir benchmark

- Cargo.lock
- cli/src/create/write_toml.rs
- mopro-ffi/Cargo.toml
- mopro-ffi/src/lib.rs
- test-e2e/Cargo.toml
- test-e2e/tests/circom.rs
- test-e2e/tests/halo2.rs
Closes #356.
Downstream crates had to depend on both `mopro_ffi` and `uniffi` in `Cargo.toml`.  
This duplicated dependencies, risked version mismatches, and cluttered project manifests.
1. **UniFFI re-export**  
The new `uniffi` feature (not enabled by default) re-exports all UniFFI crates items:
```rust
#[cfg(feature = "uniffi")]
pub use uniffi::*;
```
2. **Crate-alias macro**  
UniFFI’s macros reference `::uniffi::*` directly.     To satisfy them, we introduce `uniffi_setup!()`, which shadows the crate name:
```rust
#[cfg(feature = "uniffi")]
#[macro_export]
macro_rules! uniffi_setup {
() => {
extern crate mopro_ffi as uniffi;
};
}
```
The `app!` macro now expands this automatically; downstream code needs no changes.
3. **Testing support**  
Added a companion feature `uniffi-test` that …
> feat: add optional `uniffi` re-export via `mopro_ffi`

- test-e2e/Cargo.toml
The override was a workaround for [mozilla/uniffi-rs#2346](https://github.com/mozilla/uniffi-rs/issues/2346).
That issue was fixed in uniffi 0.29.0, so the extra lint suppression is no longer required.
> fix: drop temporary Clippy lint override in `test-e2e/Cargo.toml`

- docs/docs/getting-started.md
This commit updates the link to the Architectures section in docs/docs/getting-started.md to point to the correct file (./architectures.md). The previous link was broken due to a missing or incorrect file path. This change ensures that users can access the relevant documentation without encountering a 404 error.
> Fix broken link to Architectures section in getting-started guide

- cli/src/template/mopro-wasm-lib/src/lib.rs
Update the wasm-bindgen documentation URL from the old broken link
to the correct current documentation URL.
- Changed from: https://rustwasm.github.io/wasm-bindgen/reference/types.html
- Changed to: https://rustwasm.github.io/docs/wasm-bindgen/reference/types.html
This fixes the broken reference link in the template library file.
> fix: update broken wasm-bindgen documentation link

- docs/docs/setup/rust-setup.md
- Add .md extension to ios-setup and android-setup links on line 239
- Resolves documentation build errors where links were pointing to non-existent files
> fix: add .md extension to ios-setup and android-setup links in rust-setup.md

- cli/Cargo.toml
- cli/README.md
- cli/src/bindgen.rs
- cli/src/init.rs
- cli/src/main.rs
- docs/docs/setup/rust-setup.md
close #366 
- use `mopro bindgen` to generate bindings in the folder where executing the command
- requires to input a circuit folder e.g. `test-vectors/circom`
- it copies the keys to folder created by `mopro init` e.g. `project/test-vectors/circom`
- replace the `src/lib.rs` to compile the rust-witness functions
- run `mopro build` for selected architecture
- output a `MoproiOSBindings` or `MoproAndroidBindings` in the root folder and delete the temp project
- TODOs in the future PR
- support `witnesscalc_adapter`
- add output path
- remove helping messages (it prints all `mopro init`,  `mopro build` messages)
> Feat cli bindgen

- mopro-ffi/src/app_config/mod.rs
changed the code to call `parse_from_str` on `A` instead of `Arch` so it uses the right type.
this fixes the bug and keeps it generic.
> fix: parse call to use generic type instead of Arch

- .github/workflows/build-and-test.yml
GitHub-hosted runners now use Node 24, so actions/checkout@v5 is required. Minimum runner version v2.327.1. Workflows only updated—no functional changes.
See: https://github.com/actions/checkout/releases/tag/v5.0.0
> chore(ci): upgrade checkout to v5

- docs/versioned_docs/version-0.1.0/prerequisites.md
https://rustwasm.github.io/wasm-pack/installer/ was broken so i decided to replace it with the correct one:
https://drager.github.io/wasm-pack/installer/
> docs: fix broken link in prerequisites.md

- cli/README.md
- cli/src/bindgen.rs
- cli/src/build.rs
- cli/src/create/utils.rs
- cli/src/init.rs
- cli/src/main.rs
Fixes #517 
#$ Summary
- Added new `--adapter` and `--output-dir` options to `mopro bindgen`, enabling witness generation via `witnesscalc` and writing bindings to a chosen location.
- Introduced a quiet mode for initialization and build steps to suppress instructional output while still allowing regular usage to display messages.
- Updated documentation and README to describe the new witness generator and output directory options for `bindgen`
> Added new options to mopro bindgen

- mopro-ffi/src/app_config/mod.rs
- test-e2e/tests/bindings/test_circom_keccak.swift
- test-e2e/tests/bindings/test_circom_multiplier2.swift
- test-e2e/tests/bindings/test_circom_multiplier2_bls.swift
- test-e2e/tests/bindings/test_gemini_fibonacci.swift
- test-e2e/tests/bindings/test_halo2_keccak256.swift
- test-e2e/tests/bindings/test_hyperplonk_fibonacci.swift
- test-e2e/tests/bindings/test_noir_multiplier2.kts
- test-e2e/tests/bindings/test_noir_multiplier2.swift
- test-e2e/tests/bindings/test_plonk_fibonacci.swift
- Updates project name formatting to use PascalCase for mobile platform naming conventions
- Standardizes import statements across test files to use consistent naming
This ensures FFI bindings follow mobile platform naming conventions where:
- iOS frameworks use PascalCase (e.g., MoproBindings)
- Android packages follow similar capitalization patterns
- Breaking Change: Projects using the old mopro_bindings import will need to
update to MoproBindings
- Compatibility: Improves consistency with mobile platform naming
conventions
- Developer Experience: More intuitive import names for mobile developers
- Completes the FFI naming convention improvements started in PR #548
- Closes #500
> FFI: binding naming consistency for mobile platforms

- .github/workflows/build-and-test.yml
- cli/src/init.rs
- cli/src/init/write_toml.rs
- cli/src/template/init/tests/bindings/circom/test_multiplier2.kts
- cli/src/template/init/tests/bindings/circom/test_multiplier2.swift
- cli/src/template/init/tests/bindings/halo2/test_gemini_fibonacci.kts
- cli/src/template/init/tests/bindings/halo2/test_gemini_fibonacci.swift
- cli/src/template/init/tests/bindings/halo2/test_hyperplonk_fibonacci.kts
- cli/src/template/init/tests/bindings/halo2/test_hyperplonk_fibonacci.swift
- cli/src/template/init/tests/bindings/halo2/test_plonk_fibonacci.kts
- cli/src/template/init/tests/bindings/halo2/test_plonk_fibonacci.swift
- Fixed generated Swift/Kotlin binding tests:
- Replaced the default `mopro` import with the project-specific library name.
- Updated the CLI `init` flow to rewrite the `// GENERATED LIB IMPORT` placeholder for both:
- Swift → `import <project_name>`
- Kotlin → `import uniffi.<project_name>.*`
- Added a CI job that ensures React Native apps created via `mopro` can be built successfully:
- Runs `expo prebuild` to generate native projects.
- Verifies iOS builds headlessly with `xcodebuild`.
- Verifies Android builds headlessly with Gradle (`assembleDebug`).
This fixes #567 and makes sure that we never miss similar issues in the future by implementing #570.
> fix: resolve React Native compilation issues and add CI build checks
